config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get "todos", to: "todos#index"
  #post "todos", to: "todos#create"
  #get "todos/:id", to: "todos#show"
  get "/" => "home#index"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  resources :todos
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text ,presence: true
  validates :due_date ,presence: true
  validates :todo_text, length: {minimum: 2}
  belongs_to :user

  def self.overdue
    all.where(" due_date< ?", Date.today)
  end

  def self.due_today
    all.where("due_date= ?", Date.today)
  end

  def self.due_later
    all.where("due_date> ?", Date.today)
  end

  def self.show_list
    puts "My Todo-list\n\n"
    puts "Overdue\n"
    puts overdue.map { |todo| todo.to_displayable_string }

    puts "\n\n"
    puts "Due Today\n"
    puts due_today.map { |todo| todo.to_displayable_string }
    puts "\n\n"

    puts "Due Later\n"
    puts due_later.map { |todo| todo.to_displayable_string }
    puts "\n\n"
  end

  def to_pleasent_string
    is_completed = completed ? "[x]" : "[ ]"
    "#{id} .  #{due_date.to_s(:long)} #{todo_text} #{is_completed}"
  end

  def self.completed
    all.where(completed: true)
  end

  def self.notcompleted
    all.where(completed: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :todos
  validates :first_name ,presence: true
  validates :email ,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Invalid Login. Please try again"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    # render plain: Todo.all.map { |todo| todo.to_pleasent_string }.join("\n")
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = current_user.todos.find(id)
    # render plain: todo.to_pleasent_string
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    if new_user.save
      session[:current_user_id] = new_user.id
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<main>
  <h1 class="Home-title">Welcome to the Todo Manager</h1>
  <h3 class="Home-authenticate">If you are an existing User, <%= link_to "sign in here", new_sessions_path%> </p>
  <h3 class="Home-authenticate">If you are a new User, <%= link_to "sign up here", new_user_path%> </h3>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
     <p class="UserHeader">
      TodoManager
      <%= link_to "Sign-Out", destroy_session_path, method: "delete" %>
     </p>
     <hr>
    <% end %>
    <% if flash[:error] %>
    <p class="Flash-error">
      <%=flash[:error] %>
    </p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
 <section class="TodoSection">
        <div class="TodoSectionTitle">
          <p class="TodoSectionTitle-text"><%=section_title%></p>
          <p class="TodoSectionTitle-remainingcount"><%= todos.completed.count %>/<%=todos.count%></p>
        </div>
        <ul>
          <% todos.all.each do |todo|%>
              <li class="TodoItem">
              <%= form_with(url: "/todos/#{todo.id}", method: "put",name: "check") do %>
                <input class="TodoItem-checkbox"
                 type="checkbox"
                 name="completed"
                 value: <%= todo.completed ? "checked" : ""%>
                  onclick="this.form.submit()"
                 />
              <%end%>
                <p class='<%= todo.completed ? "TodoItemText-striked" : ""%>'><%= todo.todo_text%></p>
                <% if show_due_date%>
                    <p class="TodoItem-duedate"><%=todo.due_date.to_s(:short)%></p>
                  <%end%>
                  <a class="TodoItem-delete" "href=" javascript:void(0)">
                   <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
                      <%=image_submit_tag("trash-can-outline.svg")%>
                   <%end%>
                  </a>
            </li>
         <%end%>
        <ul>
 </section>

app/views/todos/index.html.erb
 <main class="TodoPageMain">

    <article>
      <h1 class="TodoPage-title"><%= @current_user.first_name %>'s-TodoList</h1>
      <%= form_with(url: "/todos",method: "post",class: "AddTodo") do %>
        <%=text_field_tag 'todo_text', nil, placeholder: "What's next", class: "AddTodo-text"%>
        <%=date_field_tag 'due_date', nil, class: 'AddTodo-date'%>
        <%=submit_tag  nil, class: "AddTodo-button", value: "Add"%>
      <%end%>
      <%= render partial: "todo-section" , locals:
       {section_title: "Overdue",
        todos: @todos.overdue.notcompleted,
        show_due_date: true,
       }%>
       <%= render partial: "todo-section" , locals:
       {section_title: "Due Today",
        todos: @todos.due_today,
        show_due_date: false,
       }%>
       <%= render partial: "todo-section" , locals:
       {section_title: "Due Later",
        todos: @todos.due_later,
        show_due_date: true,
       }%>

  </article>
  </main>

app/views/users/new.html.erb
<main>
  <p class="NewUsers-title">Welcome new user!</p>

  <section class="UserNew">

    <%= form_with url:users_path do |form| %>
      <div class="Form-section">
        <p class="FormInput-label">First Name ;</p>
        <%= form.text_field :first_name, class: "Form-Input" %>
      </div>
      <div class="Form-section">
        <p class="FormInput-label">Last Name :</p>
        <%= form.text_field :last_name, class: "Form-Input"%>
      </div>
      <div class="Form-section">
        <p class="FormInput-label">Email :</p>
        <%= form.email_field :email, class: "Form-Input"%>
      </div>
      <div class="Form-section">
        <p class="FormInput-label">Password :</p>
        <%= form.password_field :password, class: "Form-Input"%>
      </div>
      <div class="Form-section">
        <%= form.submit "Sign-up!", class: "Form-submit"%>
      </div>
    <%end%>
  </section>
</main>